### ISSUE TITLE
extension picks up the wrong url

### ISSUE THREAD

**Issue by simoneb** [nearform/github-snooze-chrome-extension#202]
![image](https://user-images.githubusercontent.com/20181/193852315-005c6986-f62c-43cd-a5a5-0112dbb61c9e.png)

**Comment by brunopascottini** [comment]
The onActivated event of chrome was correctly triggered and the url of the active tab was written in chrome's local storage and displayed. I could not reproduce the issue during my investigation. I am happy to dive deeper into this if needed.

**Comment by simoneb** [comment]
I think I had already commented on one of the earlier PRs about the storage of the url as a possible cause of bug, and I think we're hitting that now. I wonder why we're storing the url in the first place, rather than grabbing it when we need it. I think that avoiding storing it is ultimately the solution to this issue.

As an example, maybe onActivated is simply not called when we think it is, leading to an old url lying around.
